python train.py --summary_interval=200 \
                --max_length=10 \
                --num_bits=8 \
                --max_repeats=10 \
                --hidden_size=512 \
                --depth=2 \
                --memory_size=128 \
                --word_size=20 \
                --num_read_heads=1 \
                --checkpoint_dir=/media/storage/dnc/runs/repeat_copy/10_10/rawtgu512x2/bs16/lr1e-4 \
                --batch_size=5 \
                --learning_rate=1e-4 \
                --controller_type=tgu \
                --num_training_iterations=35000 \
                --use_dnc=False \
                --checkpoint_interval=500

python train.py --summary_interval=200 \
                --max_length=10 \
                --num_bits=8 \
                --max_repeats=10 \
                --hidden_size=512 \
                --depth=2 \
                --memory_size=128 \
                --word_size=20 \
                --num_read_heads=1 \
                --checkpoint_dir=/media/storage/dnc/runs/repeat_copy/10_10/rawlstm512x2/bs16/lr1e-4 \
                --batch_size=5 \
                --learning_rate=1e-4 \
                --controller_type=lstm \
                --num_training_iterations=35000 \
                --use_dnc=False \
                --checkpoint_interval=500

python train.py --summary_interval=200 \
                --max_length=10 \
                --num_bits=8 \
                --max_repeats=10 \
                --hidden_size=100 \
                --depth=1 \
                --memory_size=128 \
                --word_size=20 \
                --num_read_heads=1 \
                --checkpoint_dir=/media/storage/dnc/runs/repeat_copy/10_10/dnctgu100/bs16/lr1e-4 \
                --batch_size=5 \
                --learning_rate=1e-4 \
                --controller_type=tgu \
                --use_dnc=True \
                --num_training_iterations=35000 \
                --checkpoint_interval=500

python train.py --summary_interval=200 \
                --max_length=10 \
                --num_bits=8 \
                --max_repeats=10 \
                --hidden_size=100 \
                --depth=1 \
                --memory_size=128 \
                --word_size=20 \
                --num_read_heads=1 \
                --checkpoint_dir=/media/storage/dnc/runs/repeat_copy/10_10/dnclstm100/bs16/lr1e-4 \
                --batch_size=5 \
                --learning_rate=1e-4 \
                --controller_type=lstm \
                --use_dnc=True \
                --num_training_iterations=35000 \
                --checkpoint_interval=500
